### ISSUE TITLE
Date/Time Format

### ISSUE THREAD

**Issue by jheredianet** [jheredianet/Teslamate-CustomGrafanaDashboards#16]
### Discussed in https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/discussions/15

<div type='discussions-op-text'>

<sup>Originally posted by **rikardronnkvist** January 18, 2023</sup>
Would suggest that you use dateTimeAsSystem instead of dateTimeAsLocal for date and time

Something like this: adriankumpf/teslamate#3053

For example the dashboard Current State have a last state change where the dateformat is based on the operating system instead of what I have specified for the Grafana-container.</div>

**Comment by jheredianet** [comment]
I've been researching about your suggestion. The more the user can customize how they want to see their data, the better.
You got the changes in the [developer branch](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/tree/develop). Dashboards: Current State and Charging Costs Stats.
Let me know if it works as expected so I can merge them into the main branch.

**Comment by rikardronnkvist** [comment]
Can't really see where the date is on Charging Costs Stats but the Current State works fine.

**Comment by jheredianet** [comment]
On Charging Costs Stats dashboard, At the button you have a Collapsed row: "Monthly Stats", expand it and you will see them like the following screenshot. 

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/45735191/213171383-64f1c507-26a5-433b-bd1a-4a5d78505993.png">

**Comment by rikardronnkvist** [comment]
Ah...  there it is, and it looks great. :)
