### ISSUE TITLE
Car battery model recognition error

### ISSUE THREAD

**Issue by SiNaPsEr0x** [jheredianet/Teslamate-CustomGrafanaDashboards#17]
Hello @jheredianet I noticed that my sr+2020 with 50,000km of recharge logs anyway is on your db appears to me with a wrong data.. mine came out with 50kwh

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/5438823/213455032-81f8d374-0435-49cc-86bf-b9c9f3214099.png">

Also after the last refills from % wrong

**Comment by jheredianet** [comment]
Hi, could you check this https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/issues/14
Maybe it could help. Try to run the queries in order to find out if you have some some wrong data.
