### ISSUE TITLE
docker container doesn't have permission to access customdashboards.yml

### ISSUE THREAD

**Issue by QuanDev2** [jheredianet/Teslamate-CustomGrafanaDashboards#23]
I ran docker-compose and got hit with this error:
`logger=server t=2023-01-26T04:28:27.37+0000 lvl=eror msg="Server shutdown" error="*provisioning.ProvisioningServiceImpl run error: Failed to create provisioner: Failed to read dashboards config: could not parse provisioning config file: customdashboards.yml error: open /etc/grafana/provisioning/dashboards/customdashboards.yml: permission denied",
*provisioning.ProvisioningServiceImpl run error: Failed to create provisioner: Failed to read dashboards config: could not parse provisioning config file: customdashboards.yml error: open /etc/grafana/provisioning/dashboards/customdashboards.yml: permission denied`

Here's my grafana service in docker-compose:
`  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=teslamodely2023!
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
      - ./Teslamate-CustomGrafanaDashboards/customdashboards.yml:/etc/grafana/provisioning/dashboards/customdashboards.yml
      - ./Teslamate-CustomGrafanaDashboards/dashboards:/TeslamateCustomDashboards`

I checked the perms on the Teslamate-CustomGrafanaDashboards dir and verified that all the files have full permissions.
What gives?

**Comment by QuanDev2** [comment]
For those who has the same issue, try this: https://community.grafana.com/t/new-docker-install-with-persistent-storage-permission-problem/10896/5

I tried solution 2, it worked.

**Comment by jheredianet** [comment]
Hey! I'm glad you found a solution for this. It usally happens when your user (uid) is not the same as the user running docker service (with no privilegies on your home path). Other solution for this, is to use an absolute path where the users have the correct permissions as explained here https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards#using-other-path-for-repository

Cheers!
