### ISSUE TITLE
Geofence name with supercharger not included in some dashboards

### ISSUE THREAD

**Issue by jheredianet** [jheredianet/Teslamate-CustomGrafanaDashboards#33]
### Discussed in https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/discussions/32

<div type='discussions-op-text'>

<sup>Originally posted by **vincep5** March 31, 2023</sup>
Some of the queries should be updated so that if I make a Geofence for Tesla Superchargers, they get included.
Some of my recent charging sessions didnt have the address name with the text "Supercharger" so they seem to be excluded from several dashboards and its queries.  Example of one is the Charging Costs Stats</div>

**Comment by jheredianet** [comment]
Fixed on [release v2.8.4  ](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/releases/tag/v2.8.4)

**Comment by vincep5** [comment]
thanks, looks good
