### ISSUE TITLE
Battery Health - Usable (New) completely off - 3.0.5

### ISSUE THREAD

**Issue by denzel1994** [jheredianet/Teslamate-CustomGrafanaDashboards#38]
Hey,

today I updated from 2.8.3 to 3.0.5 and noticed that the value for Usable (New) is completely off.
I drive a late 2021 Model 3 SR+ with 60 kWh battery. Maximum full when new should be somewhere around 60.5 kWh, but I am getting 83.7 kWh.

<img width="1651" alt="Bildschirmfoto 2023-07-19 um 23 18 42" src="https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/36551243/d2989616-a5d5-456f-b2a7-b052f5cdaa05">

With 2.8.3 it was not that far off.
<img width="820" alt="Bildschirmfoto 2023-07-20 um 01 24 25" src="https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/36551243/2f3ed017-8838-498e-a483-ea9647e66423">

Thank you for your help and awesome work on the dashboards.

**Comment by jheredianet** [comment]
Hi, this could be happening because some wrong data from a charging session. Have you imported data from another system or manually registered a charge session?

What you can do it try to find wich record is with the following sentence:

`
WITH
aux	AS
(
	SELECT cp.charge_energy_added,
		cp.car_id, (SELECT efficiency FROM cars WHERE id = 1) * 100.0 AS rated_efficiency,
		(cp.end_rated_range_km - cp.start_rated_range_km) AS added_range_km
	FROM charging_processes cp
		JOIN (SELECT charging_process_id, MAX(date) as date
		FROM charges
		GROUP BY charging_process_id) AS last_charges
		ON cp.id = last_charges.charging_process_id
		INNER JOIN charges c
		ON c.charging_process_id = cp.id AND c.date = last_charges.date
	WHERE cp.car_id = 1
		AND cp.end_date IS NOT NULL
		AND cp.end_rated_range_km > cp.start_rated_range_km
	ORDER BY cp.end_date DESC 
	LIMIT 1
),  
MaxCapacity AS
(
	SELECT MAX(c.rated_battery_range_km * cars. Efficiency * 100.0 / c.usable_battery_level) AS MaxCapacity, last_charges.date
	FROM charging_processes cp
		JOIN (SELECT charging_process_id, MAX(date) as date
		FROM charges
		GROUP BY charging_process_id) AS last_charges
		ON cp.id = last_charges.charging_process_id
		INNER JOIN charges c
		ON c.charging_process_id = cp.id AND c.date = last_charges.date
		INNER JOIN cars ON cp.car_id = cars.id
	WHERE cp.car_id = 1
		AND cp.end_date IS NOT NULL
		AND cp.end_rated_range_km > cp.start_rated_range_km
		AND c.charge_energy_added >= cars. Efficiency
    GROUP BY last_charges.date
)
SELECT * from MaxCapacity ORDER BY MaxCapacity DESC
`

The first record will give you the date that is the wrong or suspect charging session, to know where that 83.7kWh is coming from. Then from the charges dashboard you can browse that date and analyse better what is wrong in order to fix, update or delete that charging session.

**Comment by denzel1994** [comment]
Hi, I ran the sentence and got the following output:
<img width="281" alt="Bildschirmfoto 2023-07-20 um 21 49 31" src="https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/36551243/d498645a-6202-42d7-b591-f5e044e34c2a">

Checking the top 4 charges I did nit find anything wrong with the charges, but a similarity. All charges started with a SoC of just 0-1%.
<img width="1635" alt="Bildschirmfoto 2023-07-20 um 22 03 02" src="https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/36551243/e6372392-fb81-4281-86e5-c260a32bb7a6">
<img width="1643" alt="Bildschirmfoto 2023-07-20 um 22 04 18" src="https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/36551243/d3252117-dcbf-4edf-8017-754810dd594c">
<img width="1639" alt="Bildschirmfoto 2023-07-20 um 22 04 47" src="https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/36551243/5f2f9f6f-6987-4ad3-8aa3-28de2aa6c1eb">
<img width="1647" alt="Bildschirmfoto 2023-07-20 um 22 05 24" src="https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/36551243/030d6401-9b62-4d79-a749-08e39464f235">

**Comment by jheredianet** [comment]
Hi, I think you got the 2 wrong charging sessions. As I see in the screenshot, they are from 2022-09-20 AND 2023-03-03. They are not giving a corresponding value to your battery capacity. It's true that is nothing strange here but the calculation is made from the charges table, so you'll need to analyze and browse it. Get the corresponding **charging_process_id** of those ones and browse the data in order to catch a wrong value. You could use this query:
`SELECT * from charges WHERE charging_process_id = XXX;`

Where XXX is the charging_process_id. You could also use the "Incomplete Data" dashboard in order to see if you have an opened charging session. If so, the way you can fix them is using the official procedure here: [Manually fixing data](https://docs.teslamate.org/docs/maintenance/manually_fixing_data). From this link you can also learn how to get the **charging_process_id**.

**Comment by denzel1994** [comment]
Hey there,

luckily no incomplete data.
My efficiency is 13.771.

Here is the data I got:

**<details><summary>Charge 198 - 2022-09-20:</summary>**
<p>



capacity | id | date | battery_heater_on | battery_level | charge_energy_added | charger_actual_current | charger_phases | charger_pilot_current | charger_power | charger_voltage | fast_charger_present | conn_charge_cable | fast_charger_brand | fast_charger_type | ideal_battery_range_km | not_enough_power_to_heat | outside_temp | charging_process_id | battery_heater | battery_heater_no_power | rated_battery_range_km | usable_battery_level
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
83.7 | 52659 | 2022-09-20 18:56:20.797 | false | 1 | 0.420 | 0 | 2 | 0 | 0 | 2 | false | IEC | <invalid> | <invalid> | 6.08 |   | 12.5 | 198 | false |   | 6.08 | 1
83.7 | 52658 | 2022-09-20 18:56:00.404 | false | 1 | 0.420 | 16 | 2 | 16 | 11 | 231 | false | IEC | <invalid> | <invalid> | 6.08 |   | 12.5 | 198 | false |   | 6.08 | 1
62.7 | 52657 | 2022-09-20 18:55:39.854 | false | 1 | 0.310 | 16 | 2 | 16 | 11 | 231 | false | IEC | <invalid> | <invalid> | 4.55 |   | 12.5 | 198 | false |   | 4.55 | 1
62.7 | 52656 | 2022-09-20 18:55:18.805 | false | 1 | 0.310 | 16 | 2 | 16 | 11 | 231 | false | IEC | <invalid> | <invalid> | 4.55 |   | 12.5 | 198 | false |   | 4.55 | 1
52.3 | 52655 | 2022-09-20 18:54:57.605 | false | 1 | 0.100 | 16 | 2 | 16 | 11 | 232 | false | IEC | <invalid> | <invalid> | 3.80 |   | 12.5 | 198 | false |   | 3.80 | 1
52.3 | 52654 | 2022-09-20 18:54:37.214 | false | 1 | 0.100 | 16 | 2 | 16 | 11 | 230 | false | IEC | <invalid> | <invalid> | 3.80 |   | 12.5 | 198 | false |   | 3.80 | 1
41.9 | 52653 | 2022-09-20 18:54:16.254 | false | 1 | 0 | 16 | 2 | 16 | 11 | 231 | false | IEC | <invalid> | <invalid> | 3.04 |   | 12.5 | 198 | false |   | 3.04 | 1
41.9 | 52651 | 2022-09-20 18:53:50.164 | false | 1 | 0 | 4 | 2 | 16 | 2 | 232 | false | IEC | <invalid> | <invalid> | 3.04 |   | 12.5 | 198 | false |   | 3.04 | 1
41.9 | 52652 | 2022-09-20 18:53:55.850 | false | 1 | 0 | 6 | 2 | 16 | 3 | 230 | false | IEC | <invalid> | <invalid> | 3.04 |   | 12.5 | 198 | false |   | 3.04 | 1

</p>
</details> 

**<details><summary>Charge 287 - 2023-03-03:</summary>**
<p>



capacity | id | date | battery_heater_on | battery_level | charge_energy_added | charger_actual_current | charger_phases | charger_pilot_current | charger_power | charger_voltage | fast_charger_present | conn_charge_cable | fast_charger_brand | fast_charger_type | ideal_battery_range_km | not_enough_power_to_heat | outside_temp | charging_process_id | battery_heater | battery_heater_no_power | rated_battery_range_km | usable_battery_level
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
78.5 | 94376 | 2023-03-03 20:38:19.083 | false | 2 | 0.790 | 16 | 2 | 16 | 11 | 230 | false | IEC | <invalid> | <invalid> | 5.70 |   | 6 | 287 | false |   | 5.70 | 1
78.5 | 94375 | 2023-03-03 20:37:58.849 | false | 1 | 0.790 | 16 | 2 | 16 | 11 | 230 | false | IEC | <invalid> | <invalid> | 5.70 |   | 6 | 287 | false |   | 5.70 | 1
71.7 | 94386 | 2023-03-03 20:41:41.488 | false | 2 | 1.43 | 16 | 2 | 16 | 11 | 231 | false | IEC | <invalid> | <invalid> | 10.4 |   | 6 | 287 | false |   | 10.4 | 2
71.7 | 94387 | 2023-03-03 20:42:01.713 | false | 3 | 1.43 | 0 |   | 16 | 0 | 3 | false | <invalid> | <invalid> | <invalid> | 10.4 |   | 6 | 287 | false |   | 10.4 | 2
66.1 | 94374 | 2023-03-03 20:37:38.678 | false | 1 | 0.660 | 16 | 2 | 16 | 11 | 231 | false | IEC | <invalid> | <invalid> | 4.80 |   | 6 | 287 | false |   | 4.80 | 1
65.5 | 94384 | 2023-03-03 20:41:00.994 | false | 2 | 1.31 | 16 | 2 | 16 | 11 | 231 | false | IEC | <invalid> | <invalid> | 9.51 |   | 6 | 287 | false |   | 9.51 | 2
65.5 | 94385 | 2023-03-03 20:41:21.239 | false | 2 | 1.31 | 16 | 2 | 16 | 11 | 232 | false | IEC | <invalid> | <invalid> | 9.51 |   | 6 | 287 | false |   | 9.51 | 2
63.8 | 94373 | 2023-03-03 20:37:18.466 | false | 1 | 0.640 | 16 | 2 | 16 | 11 | 231 | false | IEC | <invalid> | <invalid> | 4.63 |   | 6 | 287 | false |   | 4.63 | 1
58.2 | 94383 | 2023-03-03 20:40:40.817 | false | 2 | 1.16 | 16 | 2 | 16 | 11 | 230 | false | IEC | <invalid> | <invalid> | 8.45 |   | 6 | 287 | false |   | 8.45 | 2
58.2 | 94382 | 2023-03-03 20:40:20.621 | false | 2 | 1.16 | 16 | 2 | 16 | 11 | 230 | false | IEC | <invalid> | <invalid> | 8.45 |   | 6 | 287 | false |   | 8.45 | 2
51.8 | 94381 | 2023-03-03 20:40:00.383 | false | 2 | 1.04 | 16 | 2 | 16 | 11 | 231 | false | IEC | <invalid> | <invalid> | 7.53 |   | 6 | 287 | false |   | 7.53 | 2
51.8 | 94379 | 2023-03-03 20:39:19.903 | false | 2 | 1.04 | 16 | 2 | 16 | 11 | 230 | false | IEC | <invalid> | <invalid> | 7.53 |   | 6 | 287 | false |   | 7.53 | 2
51.8 | 94380 | 2023-03-03 20:39:40.151 | false | 2 | 1.04 | 16 | 2 | 16 | 11 | 230 | false | IEC | <invalid> | <invalid> | 7.53 |   | 6 | 287 | false |   | 7.53 | 2
51.4 | 94372 | 2023-03-03 20:36:58.221 | false | 1 | 0.510 | 16 | 2 | 16 | 11 | 230 | false | IEC | <invalid> | <invalid> | 3.73 |   | 6 | 287 | false |   | 3.73 | 1
51.4 | 94371 | 2023-03-03 20:36:37.983 | false | 1 | 0.510 | 16 | 2 | 16 | 11 | 230 | false | IEC | <invalid> | <invalid> | 3.73 |   | 6 | 287 | false |   | 3.73 | 1
51.4 | 94370 | 2023-03-03 20:36:17.775 | false | 1 | 0.510 | 16 | 2 | 16 | 11 | 230 | false | IEC | <invalid> | <invalid> | 3.73 |   | 6 | 287 | false |   | 3.73 | 1
45.5 | 94378 | 2023-03-03 20:38:59.672 | false | 2 | 0.910 | 16 | 2 | 16 | 11 | 230 | false | IEC | <invalid> | <invalid> | 6.61 |   | 6 | 287 | false |   | 6.61 | 2
45.5 | 94377 | 2023-03-03 20:38:39.365 | false | 2 | 0.910 | 16 | 2 | 16 | 11 | 230 | false | IEC | <invalid> | <invalid> | 6.61 |   | 6 | 287 | false |   | 6.61 | 2
38.8 | 94369 | 2023-03-03 20:35:57.582 | false | 1 | 0.390 | 16 | 2 | 16 | 11 | 230 | false | IEC | <invalid> | <invalid> | 2.82 |   | 6 | 287 | false |   | 2.82 | 1
38.8 | 94368 | 2023-03-03 20:35:37.264 | false | 1 | 0.390 | 16 | 2 | 16 | 11 | 230 | false | IEC | <invalid> | <invalid> | 2.82 |   | 6 | 287 | false |   | 2.82 | 1


</p>
</details> 


I guess I got these issues, because these charges where so short and at a very low state of charge.

Is always the capacity value at the end of a charge selected or an average for the complete charge?

Thank you very much again for your help and the very detailed step-by-step guide.

Regards

**Comment by jheredianet** [comment]
Hi, you got it!

I guess you had those records because of a miss calibration of the BMS. 

As we can see the "rated_battery_range_km" has some strange values

![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/45735191/5571a9a4-4b0b-4344-ae33-dc0fbd848563)


Here you have the option of: delete those single records (they won't affect your data logged).
I guess it could be something about LFP batteries (because of the BMS calibration).
About the capacity there are 2 calculations one for an average of the last 5 charges (which in your case is right) and the other to get the max capacity of all the full data logged.

At the begging you said that in v2.8.3 was working OK right? Let me check if it is possible to merge those formulas to improve this calculation.

**Comment by denzel1994** [comment]
Hi,

what is strange about the "rated_battery_range_km" values?
Are those not more accurate than the usable battery level, which has no decimals?

**Comment by jheredianet** [comment]
Hi, 
It's strange (in the previous sample) because: rated_battery_range_km * 13.771 / usable_battery_level (6.08 / 13.771  * 1 = 83.72768) it should be something like the 3 or 4 record. 

I mean the car was telling that with 1% you got 4.5km and then a second after it says you got 6.08km with the same SOC.

**Comment by denzel1994** [comment]
Hi, 

you are correct, but you have this with every charging session.
Here an example from a different charging session, which wasn't in the list shown here: https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/issues/38#issuecomment-1644535072

<img width="928" alt="Bildschirmfoto 2023-07-21 um 12 35 02" src="https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/36551243/606de98d-69db-41f9-be0b-42aac51161ca">

There is an inaccuracy in the calculation since the battery level is a whole number with no decimals.
When you take a look at the third column "charge_energy_added" you see that when it rises so does the rated battery range. So instead of 1% the battery level actually is 1.2% at that point.

**Comment by jheredianet** [comment]
Yes, you are right, it's because of the decimals. 
Could you run this query? This is to see what we get on each SOC of a charging session. Especially on the charging_process_id=198  where you are getting 83.7 as max. Then try charging_process_id=287 as well. 
I need to see if it fine tunes the calculation.

`
SELECT AVG(rated_battery_range_km * 13.771 / usable_battery_level) as Capacity 
from charges 
WHERE charging_process_id=198
GROUP BY usable_battery_level
ORDER BY 1 DESC
LIMIT 1;
`

**Comment by denzel1994** [comment]
Had to adjust the query a little to avoid divisions with 0 (when usable_bettery_level = 0%), because I have those in charge 287.

`SELECT AVG(rated_battery_range_km * 13.771 / usable_battery_level) as Capacity  from charges  WHERE charging_process_id=198 AND usable_battery_level > 0 GROUP BY usable_battery_level ORDER BY 1 DESC LIMIT 1;`

These are the results. Looking very good.

198 --> 58.1
287 --> 57.9

**Comment by jheredianet** [comment]
Great. I'll have to avoid 0 values; please could you share a screenshot of this?

![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/45735191/9409a89b-b5ec-4842-84d9-11d733734b78)

**Comment by denzel1994** [comment]
Here you go.

<img width="1643" alt="Bildschirmfoto 2023-07-21 um 13 07 28" src="https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/36551243/11468d45-512a-40db-8439-ecf4ffbb3630">

**Comment by jheredianet** [comment]
Thanks, so the top here is 61kWh? 
It does not show the 83.kWh?

So strange.

**Comment by denzel1994** [comment]
The max value is 60.6.

Tried the query, but no change as far as I can see:
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/36551243/e1700b67-2396-4ad8-a8ad-a4003fbc4207)

**Comment by jheredianet** [comment]
Thank you, I think I've realized what it is. 
I've made the changes and publish on the [developer branch](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/blob/develop/dashboards/BatteryHealth.json) 
Please, could you import and try? It should be fixed. If you confirm I'll create a new release with these changes.

**Comment by denzel1994** [comment]
This looks more like it. :)

Thank you very much.
<img width="1646" alt="Bildschirmfoto 2023-07-21 um 14 25 48" src="https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/36551243/5004cc06-f3e6-4b74-8dc8-c02c1ca3fca4">

**Comment by jheredianet** [comment]
Great! Thank you. 

This is solved on [release v3.0.6](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/releases/tag/v3.0.6)
