### ISSUE TITLE
Battery Health Panel - More information

### ISSUE THREAD

**Issue by guillitux** [jheredianet/Teslamate-CustomGrafanaDashboards#4]
Hello there!

Is it possible show the actual status of the battery? The same information like the Current Drive View Panel.

![image](https://user-images.githubusercontent.com/4116024/211093737-1c81259f-47e7-4638-b0fd-d97d95bb63cd.png)

Thanks in advances!

**Comment by jheredianet** [comment]
Hi @guillitux 
You got it. Could you check it and let me know if it's working?

**Comment by guillitux** [comment]
Hi @jheredianet 
It's working properly.

![image](https://user-images.githubusercontent.com/4116024/211164411-c62452e9-40d6-4ffd-ac62-7b9c1841ce8a.png)
