### ISSUE TITLE
Negative value in Charging Cost Stats

### ISSUE THREAD

**Issue by cbrandlehner** [jheredianet/Teslamate-CustomGrafanaDashboards#49]
My guess is that marking superchargers free, as I have free Supercharging for my Model S, the calculation gets confused.

![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/10800971/ba319705-890f-488c-a97e-ee31cedc650d)

**Comment by cbrandlehner** [comment]
@jheredianet thanks, here are two screenshots from "Browse Chargers":
![Bildschirmfoto 2023-09-08 um 07 53 47](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/10800971/15f581ea-2d23-4af0-836f-16d059ac7a52)
![Bildschirmfoto 2023-09-08 um 07 54 24](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/10800971/e5ae82dc-e47b-45ba-bb7f-dfc432bef17a)

**Comment by cbrandlehner** [comment]
... and another screenshot showing home, work and Supercharger in a single screenshot.
![Bildschirmfoto 2023-09-08 um 07 56 54](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/10800971/0da92847-7196-44b2-b361-3e95d9883937)

**Comment by jheredianet** [comment]
> @jheredianet thanks, here are two screenshots from "Browse Chargers": ![Bildschirmfoto 2023-09-08 um 07 53 47](https://user-images.githubusercontent.com/10800971/266515058-15f581ea-2d23-4af0-836f-16d059ac7a52.png) ![Bildschirmfoto 2023-09-08 um 07 54 24](https://user-images.githubusercontent.com/10800971/266515064-e5ae82dc-e47b-45ba-bb7f-dfc432bef17a.png)

Oh, I see it, in the second screen shot you have null values on the supercharger costs. The queries on the dashboard does not include or treat NULL values as 0. You need to set a 0 value manually for each one. 

What I don't know is is you have this option set in TeslaMate (you should check it, if you have supercharger)

![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/45735191/e5b97ad4-cb72-4ec9-bc4c-958966ce295e)

Maybe what is happening is that Teslmate some times does not recognize a place as a Supercharger by Geo-position, so you need to periodically watch the costs to avoid null values, if so, you have to put ir 0 accordingly.

**Comment by cbrandlehner** [comment]
It is enabled in the settings.
![Bildschirmfoto 2023-09-08 um 08 59 27](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/10800971/19faaddc-0213-46ef-be8f-ec5c623253eb)

Yes, I noticed that Teslamate is sometimes failing to recognize a Supercharger so I geofenced them manually.

**Comment by jheredianet** [comment]
Great!, so let me know if it's working OK when you have replaced the "--" cost values by 0.

**Comment by jheredianet** [comment]
@cbrandlehner any update about this? Is it working, ok? 
Please, let me know in order to close the issue.

**Comment by cbrandlehner** [comment]
I will not be able to spend time for the next week or so due to travel activities.

**Comment by cbrandlehner** [comment]
Free Supercharging is activated in the Teslamate Settings and charges at new superchargers are being added as NULL "-".
As you suggested I created geolocations for each supercharger and added a cost of Zero "0".
![Bildschirmfoto 2023-09-20 um 06 01 39](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/10800971/54fe475a-66e3-40d1-a870-c72c3ceeaf38)
![Bildschirmfoto 2023-09-20 um 06 02 38](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/10800971/050ce875-b1b7-43c1-9969-a362246daddc)
