### ISSUE TITLE
Charging Cost Stats shows 0 at SuC

### ISSUE THREAD

**Issue by vincep5** [jheredianet/Teslamate-CustomGrafanaDashboards#51]
The tile that shows "Charging Cost at SuC" shows 0 for me even when having several SuperCharger sessions logged
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/26965876/a4dab033-88c6-47c0-9575-43e5b75752ec)

**Comment by jheredianet** [comment]
Please could you update to the latest release?
https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/releases/tag/v3.1.0

Let me know How it goes. Cheers!

**Comment by vincep5** [comment]
The data from the Charging Stats report from Teslamate has an extra left join to geofences
For my charges, I had to create geofences as the location for my charges didnt have the text 'supercharger'
Maybe yours can follow it, too
`SELECT
	sum(cp.cost)
FROM
	charging_processes cp
LEFT JOIN 
	addresses addr ON addr.id = address_id
LEFT JOIN
  geofences geo ON geo.id = geofence_id
WHERE
  $__timeFilter(end_date)
  AND (addr.name ILIKE '%supercharger%' OR geo.name ILIKE '%supercharger%')
	AND cp.cost IS NOT NULL
	AND cp.car_id = $car_id;`

**Comment by jheredianet** [comment]
As you said, it's considered both address.name and geofence.name...

Could you run this query and show the results?

This is the complete Query for that estimation (assuming your carid is 1, if not change it accordanly):
```sql
WITH data AS (
	SELECT c.charging_process_id 
	FROM charges c
	LEFT JOIN charging_processes cp ON cp.id = c.charging_process_id
	LEFT JOIN addresses addr ON addr.id = cp.address_id
	LEFT JOIN geofences geo ON geo.id = geofence_id
	WHERE 
	        cp.car_id = 1 AND c.fast_charger_present IS true AND c.charger_voltage = 2
		AND COALESCE(geo.name, CONCAT_WS(', ', COALESCE(addr.name, nullif(CONCAT_WS(' ', addr.display_name), '')))) ILIKE '%supercharger%'
	GROUP BY 1
)
SELECT coalesce(sum(cp.cost), 0) FROM charging_processes cp, data WHERE  cp.id IN (data.charging_process_id);
```
Spliting that query, with the following you should get of all the charging sessions you have done in a "supercharger"

```sql
SELECT c.charging_process_id, COALESCE(geo.name, CONCAT_WS(', ', COALESCE(addr.name, nullif(CONCAT_WS(' ', addr.display_name), '')))) as location
	FROM charges c
	LEFT JOIN charging_processes cp ON cp.id = c.charging_process_id
	LEFT JOIN addresses addr ON addr.id = cp.address_id
	LEFT JOIN geofences geo ON geo.id = geofence_id
	WHERE 
	        cp.car_id = 1 AND c.fast_charger_present IS true AND c.charger_voltage = 2
		AND COALESCE(geo.name, CONCAT_WS(', ', COALESCE(addr.name, nullif(CONCAT_WS(' ', addr.display_name), '')))) ILIKE '%supercharger%'
	GROUP BY 1, 2
```

Let's try to find where is the mistake.

**Comment by vincep5** [comment]
0 results for each. When I remove c.charger_voltage = 2 from the WHERE then I see the results properly

**Comment by jheredianet** [comment]
Oh, I see,  charger_voltage = 2 is a way to detect that the charging session is using DC charger, the same as c.fast_charger_present.
I'm curious on What model or car do you have?
I'm not sure, but maybe some cars report DC charging in different ways. If that's the case I'll need to change the queries depending on the model. Let me know your model and I'll investigate further.

**Comment by vincep5** [comment]
Model Y LR

**Comment by jheredianet** [comment]
Ok. Thank you. 

I've made some fixes, check out the latest release, it should work Ok. 

https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/releases/new?tag=v3.1.1
