### ISSUE TITLE
natel-plotly-panel no longer available

### ISSUE THREAD

**Issue by swiffer** [jheredianet/Teslamate-CustomGrafanaDashboards#58]
natel-plotly-panel & other custom Plugins have been removed in the latest Teslamate grafana version (replaced via xy chart & geomap - natively available in latest grafana releases).

https://github.com/teslamate-org/teslamate/commit/1796294442566a8f504f0eda052603ef4228a9f7

Would be great to See custom Dashboards updated so they continue working Just fine!

![grafik](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/2990373/58be19c6-acd9-4787-806f-f7d6c63a3bfc)

**Comment by SiNaPsEr0x** [comment]
idem  ... to be fixed as battery health on the teslamateorg version works without problems

**Comment by jheredianet** [comment]
Hi, this is fixed on the latest release: https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/releases/tag/v2023.11.28
