### ISSUE TITLE
Error in battery health dashboard when sum(usable_battery_level) is zero (error divided by zero)

### ISSUE THREAD

**Issue by inigoml** [jheredianet/Teslamate-CustomGrafanaDashboards#62]
When a sum of values for usable_battery_level is zero for a long period, query error arises with a divided_by_zero and so no battery heath dashboard data is displayed. This is my case.

Aux query should deal with this issue in order to avoid that if you leave your car at zero battery (or below) for a period of time, query crashes.

![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/7486708/b3c482d9-c343-4533-8859-c1464c6b56ea)

Failing query

`WITH
aux	AS
(
	SELECT cp.charge_energy_added,
		cp.car_id, (SELECT efficiency FROM cars WHERE id = $car_id) * 100.0 AS rated_efficiency,
		(cp.end_rated_range_km - cp.start_rated_range_km) AS added_range_km
	FROM charging_processes cp
		JOIN (SELECT charging_process_id, MAX(date) as date
		FROM charges
		GROUP BY charging_process_id) AS last_charges
		ON cp.id = last_charges.charging_process_id
		INNER JOIN charges c
		ON c.charging_process_id = cp.id AND c.date = last_charges.date
	WHERE cp.car_id = $car_id
		AND cp.end_date IS NOT NULL
		AND cp.end_rated_range_km > cp.start_rated_range_km
	ORDER BY cp.end_date DESC 
	LIMIT 1
),  
CurrentCapacity	 AS
(
	SELECT AVG(Capacity) AS CurrentCapacity FROM
  (SELECT (100.0 * cp.charge_energy_added) / (GREATEST(1,MAX(usable_battery_level) - MIN(usable_battery_level))) AS Capacity	
    FROM charging_processes cp
	  INNER JOIN charges c	ON cp.id = c.charging_process_id
    INNER JOIN aux ON cp.car_id = aux.car_id
	  WHERE cp.car_id = $car_id AND cp.charge_energy_added >= aux.rated_efficiency 
    GROUP BY  cp.charge_energy_added, cp.end_date
    ORDER BY cp.end_date DESC 
    LIMIT 5
  ) AS lastEstimatedCapacity
), 
MaxCapacity AS
(
   SELECT AVG(c.rated_battery_range_km * aux.rated_efficiency  / c.usable_battery_level) AS MaxCapacity, cp.id
   FROM charging_processes cp
	JOIN (SELECT charging_process_id, MAX(date) as date FROM charges 
                    WHERE usable_battery_level > 0 GROUP BY charging_process_id) AS last_charges	
        ON cp.id = last_charges.charging_process_id
	INNER JOIN charges c ON c.charging_process_id = cp.id AND c.date = last_charges.date
	INNER JOIN positions p ON p.id = cp.position_id
        INNER JOIN aux ON cp.car_id = aux.car_id
	WHERE cp.car_id = $car_id
		AND cp.end_date IS NOT NULL
		AND cp.charge_energy_added >= aux.rated_efficiency 
	GROUP BY cp.id 
        ORDER BY 1 DESC 
        LIMIT 1
), 
CurrentRange AS
(
    SELECT
		floor(extract(epoch from date)/86400)*86400 AS timecurrent,
		sum(rated_battery_range_km) / sum(usable_battery_level) * 100 AS rated_range_km
	FROM (
		SELECT battery_level, usable_battery_level, date,  rated_battery_range_km from charges c 
		JOIN charging_processes p ON p.id = c.charging_process_id 
		WHERE p.car_id = $car_id AND usable_battery_level IS NOT NULL) AS data
	GROUP BY 1
	ORDER BY 1 DESC
	LIMIT 1
), 
MaxRange AS
(
    SELECT
		floor(extract(epoch from date)/86400)*86400 AS time,
		sum(rated_battery_range_km) / sum(usable_battery_level) * 100 AS max_rated_range_km
	FROM (
		SELECT battery_level, usable_battery_level, date,  rated_battery_range_km from charges c 
		JOIN charging_processes p ON p.id = c.charging_process_id 
		WHERE p.car_id = $car_id AND usable_battery_level IS NOT NULL) AS data
	GROUP BY 1
	ORDER BY 2 DESC
	LIMIT 1
) 
SELECT  CONCAT('{"LastChargekWhAdded": ', aux.charge_energy_added, 
  ', "LastMileageAdded" : ', convert_km(aux.added_range_km,'$length_unit'),
  ', "MaxRange": ', convert_km(MaxRange.max_rated_range_km,'$length_unit'),
  ', "CurrentRange": ',convert_km(CurrentRange.rated_range_km,'$length_unit'),
  ', "MaxCapacity": ', MaxCapacity.MaxCapacity,
  ', "CurrentCapacity": ', CASE WHEN CurrentCapacity.CurrentCapacity IS NULL THEN 1 ELSE CurrentCapacity.CurrentCapacity END,
  ', "RatedEfficiency": ',aux.rated_efficiency, '}') 
FROM MaxRange, CurrentRange, Aux, MaxCapacity, CurrentCapacity;`

**Comment by inigoml** [comment]
Here where query fails, at the sum division - sum(usable_battery_level) could be zero.

`MaxRange AS
(
    SELECT
		floor(extract(epoch from date)/86400)*86400 AS time,
		sum(rated_battery_range_km) / sum(usable_battery_level) * 100 AS max_rated_range_km`

**Comment by inigoml** [comment]
Easy fix:

`MaxRange AS
(
SELECT
    floor(extract(epoch from date)/86400)*86400 AS time,
    CASE
        WHEN sum(usable_battery_level) = 0 THEN sum(rated_battery_range_km) * 100
        ELSE sum(rated_battery_range_km) / sum(usable_battery_level) * 100
    END AS max_rated_range_km
FROM (`

**Comment by jheredianet** [comment]
Thanks for your feedback, I'll have a look and prepare a Fix. 
I'll let you know when it's ready, so you can test it before releasing a new version.

**Comment by jheredianet** [comment]
Hi, it's fixed on "develop" branch at https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/tree/develop

Please, could you test it?
