### ISSUE TITLE
Battery Health Usable Capacity incorrect

### ISSUE THREAD

**Issue by vincep5** [jheredianet/Teslamate-CustomGrafanaDashboards#64]
In the Battery Health report: Battery Capacity Usable (new) is showing up as 127.9 kWh, but the built in Battery Health dashboard shows the correct 79.6kWh.

**Comment by jheredianet** [comment]
Hi, could you tell which model/year is your car?

**Comment by vincep5** [comment]
Model Y LR 2022

**Comment by jheredianet** [comment]
> Model Y LR 2022

Please could you share a screen shot of the two charts? I'd like to see the information about the ranges.

**Comment by vincep5** [comment]
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/26965876/6e30f8af-a2bf-46b6-8d27-ab6fd1d166fa)

**Comment by sdwalker** [comment]
Seeing the same issue and a difference of 58 estimated charging cycles ion miles versus kilometers
@vincep5 If you temporarily changing your length unit from miles to kilometers do the values look sane?

**Comment by vincep5** [comment]
Oh interesting.  Yes, when I change it to KM, all the charts look
accurate.  So there must be something incorrect with the km to miles
conversion.

**Comment by jheredianet** [comment]
Great catch! I'll investigate futher.

**Comment by jheredianet** [comment]
Hi, fixed the estimations, so please update to the latest release https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/releases/tag/v2024.01.06
