### ISSUE TITLE
Charging Cost at AC Stations in the Charging Cost Stats dashboard include some DC supercharger charges

### ISSUE THREAD

**Issue by tnepveu** [jheredianet/Teslamate-CustomGrafanaDashboards#66]
The title says all , 

Supercharge, other DC stations charge (only one in my case) and total cost is good but the AC cost stats in off , after a few trials, I discovered that some but not all Tesla Supercharge are included in the Charging Cost at AC Stations :

All Supercharge have a geofence with a name starting with "Tesla Supercharger"

![Capture d’écran 2024-02-16 à 16 48 30](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/157983484/5219ca1e-a789-482f-bef6-86dd05bcb051)

**Comment by tnepveu** [comment]
my guess is that - may be - some of the supercharge does not have the DC flag (charger_voltage and/or fast_charger_present) correctly set 

So it would be a DB issue rather than a dashboard issue.

As I am totally ignorant of postgresql and sql in general for that matter , I don't know how to check my hypothesis.

Thanks in advance, love your dashboards !

**Comment by jheredianet** [comment]
> Thanks in advance, love your dashboards!
Hi, I'm glad you love the dashboards. 
About your question, for the AC charging costs, it doesn't consider the geofence or names, it's based on the "fast_charger_present" field. 
So, it could be what you say. What model is your car?

If you can run this query in your database, you will get the cost of only AC charging sessions (assuming that your carid is 1, if not change it accordantly. On dates, the same, just considering this year, you can modify it as you wish). 
So, you can have an idea why 

`
WITH data AS (
	SELECT c.charging_process_id 
	FROM charges c
	LEFT JOIN charging_processes cp ON cp.id = c.charging_process_id
	WHERE 
		cp.car_id = 1 AND NOT c.fast_charger_present
        GROUP BY 1
)
SELECT
       coalesce(sum(cp.cost) , 0)
FROM
	charging_processes cp, data
WHERE
  end_date >= '20240101'
  AND cp.cost IS NOT NULL
  AND cp.id IN (data.charging_process_id);
`

Also, you may browse your database to know how is your car logging the DC charges with this query:

`
SELECT * FROM charges 
ORDER BY date DESC
 LIMIT 10;
`

You should get something like this:
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/45735191/08d5be06-2ea5-445c-a38f-a18f692fb8ab)
