### ISSUE TITLE
 Estimated Degradation very high and Battery Capacity low

### ISSUE THREAD

**Issue by alexsahka** [jheredianet/Teslamate-CustomGrafanaDashboards#70]
I've been using TeslaMate and Grafana dashboards for the past five months, and everything was working great. Last week, I started seeing errors in the Battery Health dashboard. I followed the documentation to fix the errors and ran a script that resolved them. However, now my Battery Capacity by Mileage is showing zero (previously it fluctuated), and both Estimated Degradation and Battery Capacity have become very concerning. My Estimated Degradation is now at 31.9%, whereas it was previously around 1%.

![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/7469537/126e1017-6d2d-4f4d-b8b6-63ebc42316eb)

**Comment by jheredianet** [comment]
Hi, please, first, update to the latest version of Teslamate and let us know if this behavior is the same.

**Comment by alexsahka** [comment]
After the update, it broke again.

![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/7469537/97741983-cc3b-4650-9929-f3eaadc5586f)


> Hi, could you update to the latest version of this dashboard? (https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/releases/tag/v2024.3.21) and Teslamate (which already integrates this latest version), then, please let me know if this behavior is the same.

After the update, it broke again.

![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/7469537/97741983-cc3b-4650-9929-f3eaadc5586f)

**Comment by jheredianet** [comment]
Hi, as I can see in the screenshot, some data is showing, so I guess that the "efficiency" is not being able to get. Could you try to see what the "Efficiency" dashboard shows?
There should be something like this:

![image](https://github.com/teslamate-org/teslamate/assets/45735191/67f0fd1b-c072-4386-83f8-a948c4e6d70f)

Teslamate, in order to get this information, needs some charges sessions that at least have added more than 15kWh (more than your rated efficiency), duration more than 10 minutes and SOC less than 95%. Based on those values the Battery Health dashboard does the math and estimations. 

You should also check the "Charges" dashboard in order to browse if the charges are logged correctly, especially in the fields I've mentioned before:

![image](https://github.com/teslamate-org/teslamate/assets/45735191/f5882c9e-2868-4f4c-8186-c72f36dcfe15)

**Comment by alexsahka** [comment]
efficiency:
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/7469537/664a952b-67ee-450e-be4d-572c49ebf629)
Charges:
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/7469537/b9691266-a534-4b6c-abf4-76b89771935c)

**Comment by jheredianet** [comment]
> efficiency: 

Ok, this is what I meant in te previous message, as you see, you only have short charges (11kWh max)
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/45735191/d795a7f1-b78a-4d9a-9374-cd4110dc1111)

Based on your efficiency (219Wh/mi or 136Wh/km), you need some charges of more than 13.6 kWh. As I can see, you don't get low SOCs, try one day to charge from 20% to 80% for example.

In the meantime, if you can manage and run the queries individually, so we can catch exactly, what value is being wrong or absent. Assuming that your car_id is 1 (if not change it properly)

For CurrentCapacity: 
`
	SELECT AVG(Capacity) AS Capacity
FROM (
SELECT 
	c.rated_battery_range_km * 14 / c.usable_battery_level AS Capacity
	FROM charging_processes cp
		INNER JOIN charges c
		ON c.charging_process_id = cp.id 
                INNER JOIN aux ON cp.car_id = 1
	WHERE cp.car_id = 1
		AND cp.end_date IS NOT NULL
		AND cp.charge_energy_added >= 14
		AND c.usable_battery_level > 0
	 ORDER BY cp.end_date DESC LIMIT 10) AS lastCharges
`

For MaxCapacity:
`
	SELECT 
		MAX(c.rated_battery_range_km * 14 / c.usable_battery_level) AS Capacity
	FROM charging_processes cp
		INNER JOIN (
			SELECT charging_process_id, MAX(date) as date FROM charges WHERE usable_battery_level > 0 GROUP BY charging_process_id) AS gcharges	
			ON cp.id = gcharges.charging_process_id
		INNER JOIN charges c
		ON c.charging_process_id = cp.id AND c.date = gcharges.date
		INNER JOIN aux ON cp.car_id = 1
	WHERE cp.car_id = 1
		AND cp.end_date IS NOT NULL
		AND cp.charge_energy_added >= 14
)
`

For CurrentRange
`
    SELECT (range * 100.0 / usable_battery_level) AS range
	FROM (
		(SELECT date, rated_battery_range_km AS range, usable_battery_level AS usable_battery_level
			FROM positions	WHERE car_id = 1 AND rated_battery_range_km IS NOT NULL AND usable_battery_level > 0  ORDER BY date DESC LIMIT 1)
		UNION ALL
		(SELECT date, rated_battery_range_km AS range, usable_battery_level as usable_battery_level
			FROM charges c JOIN charging_processes p ON p.id = c.charging_process_id
			WHERE p.car_id = 1 AND usable_battery_level > 0 ORDER BY date DESC LIMIT 1)
	) AS data
	ORDER BY date DESC
	LIMIT 1
`

For MaxRange:
`
    SELECT
		floor(extract(epoch from date)/86400)*86400 AS time,
	    CASE WHEN sum(usable_battery_level) = 0 THEN sum(rated_battery_range_km) * 100
		     ELSE sum(rated_battery_range_km) / sum(usable_battery_level) * 100
	END AS range
    FROM (
		SELECT battery_level, usable_battery_level, date,  rated_battery_range_km from charges c 
		JOIN charging_processes p ON p.id = c.charging_process_id 
		WHERE p.car_id = 1 AND usable_battery_level IS NOT NULL) AS data
	GROUP BY 1
	ORDER BY 2 DESC
	LIMIT 1
`

**Comment by jheredianet** [comment]
> After the update, it broke again.
> All containers are rebooted after the update.

BTW this is not the last update. The last updates is a dashboard showing more info, you are still using an older version,  look this area:

![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/45735191/bbcc211c-7466-4aeb-9d22-f6a5bf84bf1c)

**Comment by alexsahka** [comment]
> 
> Based on your efficiency (219Wh/mi or 136Wh/km), you need some charges of more than 13.6 kWh. As I can see, you don't get low SOCs, try one day to charge from 20% to 80% for example.
> 

Thank you! After discharging the battery to 20% and then charging it back to 80%, the Battery Health statistics are now normal with no errors. Should I repeat this process periodically?  Is this considered normal behavior for the Grafana panel?

**Comment by jheredianet** [comment]
> Thank you! After discharging the battery to 20% and then charging it back to 80%, the Battery Health statistics are now normal with no errors. Should I repeat this process periodically? Is this considered normal behavior for the Grafana panel?

Great to know that. 
Yes, Batteries like to be in constant motion and sleep in different SOCs periodically. Once a month a least try to make a charge for more than 15 kWh. Let's say from 30% to 90%, 40% to 80%, 20% to 60, etc.
