### ISSUE TITLE
Current Charge View units

### ISSUE THREAD

**Issue by sdwalker** [jheredianet/Teslamate-CustomGrafanaDashboards#73]
The odometer unit shouldn't be showing km when the length unit is set to miles
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/904020/524ada7c-c6e1-42c5-846e-8ee9ffe3e434)

**Comment by sdwalker** [comment]
The estimated range units are in km as well
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/904020/6182c7a0-23f1-4b2e-8cc6-031852b0d71a)

The temperatures are correct but in Celsius instead of Fahrenheit
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/904020/91c81842-4931-4e4a-93b9-c515fc2ee256)

**Comment by jheredianet** [comment]
Fixed in this release https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/releases/tag/v2024.04.10
