### ISSUE TITLE
Current Drive View miles efficiency

### ISSUE THREAD

**Issue by sdwalker** [jheredianet/Teslamate-CustomGrafanaDashboards#74]
https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/blob/main/dashboards/CurrentDriveView.json#L588

The multiplication for the miles case causes the efficiency to be wrong

With multiplication 
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/904020/7e0e2ccd-75bc-4c4e-b853-358c4ca3596f)

Without multiplication 
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/904020/c79d6fe4-0936-4d92-ad60-b9b1edb83c29)

**Comment by jheredianet** [comment]
Thank you. Yes, it will be fixed in the next release, actually it's fixed on the "develop branch"
