### ISSUE TITLE
Tracking Drive units

### ISSUE THREAD

**Issue by sdwalker** [jheredianet/Teslamate-CustomGrafanaDashboards#76]
https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/blob/main/dashboards/TrackingDrives.json#L892 should be velocitymph

velocitymih
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/904020/20d9e70b-e8e0-43bf-abc7-9b70d464e05e)

velocitymph
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/904020/0efe15be-1748-420e-878a-636b38fb0fc4)

**Comment by sdwalker** [comment]
Another occurrence at https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/blob/main/dashboards/CurrentDriveView.json#L285

**Comment by sdwalker** [comment]
Consumption is partially broken and elevation has label and detail differences
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/904020/a75bf341-f9e4-48bb-82da-f3f8f2d3df0c)
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/904020/36a3e399-f07f-4f06-9d21-47a3767f6d5e)

**Comment by jheredianet** [comment]
Thanks. Fixed on the latest release https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/releases/tag/v2024.04.11
