### ISSUE TITLE
Mileage Stats missing miles distance

### ISSUE THREAD

**Issue by sdwalker** [jheredianet/Teslamate-CustomGrafanaDashboards#77]
Distance column is missing for miles

mi
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/904020/f11e5752-ea1e-4571-a7e4-56ff38229803)

km
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/904020/9c225a47-e7ed-4990-a4b7-6256c7570a9a)

**Comment by jheredianet** [comment]
https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/releases/tag/v2024.04.11
