### ISSUE TITLE
Browse Charges missing temp colors, mileage unit

### ISSUE THREAD

**Issue by sdwalker** [jheredianet/Teslamate-CustomGrafanaDashboards#78]
Missing colored temp text and units for the mileage column

mi
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/904020/d2ff9669-747a-44ce-b8d7-9bf660042672)

km
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/904020/b540f614-1fd0-4736-ae4c-372620c4349c)

**Comment by jheredianet** [comment]
https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/releases/tag/v2024.04.11

**Comment by sdwalker** [comment]
https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/blob/main/dashboards/BrowseCharges.json#L641 should be lengthmi and a decimals 0 property added to match the km definitions at https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/blob/main/dashboards/BrowseCharges.json#L523

**Comment by jheredianet** [comment]
> https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/blob/main/dashboards/BrowseCharges.json#L641 should be lengthmi and a decimals 0 property added to match the km definitions at https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/blob/main/dashboards/BrowseCharges.json#L523

Thank you, it's fixed on this commit https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/commit/6b7e20295b085da4a9d7cb7843e1bc29799e2a1a
It will be available in next release soon.
