### ISSUE TITLE
Remaining unit differences

### ISSUE THREAD

**Issue by sdwalker** [jheredianet/Teslamate-CustomGrafanaDashboards#79]
Continuous Trips (missing distance gauge cell type)
km
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/904020/87aff23d-fd6d-46fd-8917-e0002869f1e5)
mi
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/904020/7400baba-0472-4423-ad48-61364fd227df)

Charging Costs Stats (different column layout, missing temp colors)
km
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/904020/0072bb95-85e4-435f-ab5a-192ce809aad2)
mi
![image](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/904020/ec0ad884-3f4f-4e8c-9296-cb82ee4f9665)

**Comment by jheredianet** [comment]
Thank you, it's fixed on this commit https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/commit/6b7e20295b085da4a9d7cb7843e1bc29799e2a1a
It will be available in next release soon.
