### ISSUE TITLE
Failed to create provisioner

### ISSUE THREAD

**Issue by spacex-3** [jheredianet/Teslamate-CustomGrafanaDashboards#88]
Updating to the latest version of Teslamate (1.29.2), an error occurred using the current dashboard, and the log is as follows:

teslamate-grafana-1    | Error: ✗ Failed to create provisioner: Failed to create provisioner: Failed to read dashboards config: could not parse provisioning config file: customdashboards.yml error: read /etc/grafana/provisioning/dashboards/customdashboards.yml: is a directory
teslamate-grafana-1 exited with code 1

**Comment by jheredianet** [comment]
Be awere that ~/ in linux means home folder and ./ means actual folder (it's not the same). 

So whereever you are this means ~/data  (/home/youruser/data)
while ./data (depending on the folder your are, let's say I'm on /myfiles) it means /myfiles/data/

**Comment by spacex-3** [comment]
Ok I learn that&nbsp;
Thanks&nbsp;

发自我的iPhone


------------------ Original ------------------
From: Juan Carlos Heredia ***@***.***&gt;
Date: Tue,Jun 25,2024 11:56 PM
To: jheredianet/Teslamate-CustomGrafanaDashboards ***@***.***&gt;
Cc: fantasysk ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [jheredianet/Teslamate-CustomGrafanaDashboards] Failed to createprovisioner (Issue #88)





 
Be awere that ~/ in linux means home folder and ./ means actual folder (it's not the same).
 
So whereever you are this means ~/data  (/home/youruser/data)
 while ./data (depending on the folder your are, let's say I'm on /myfiles) it means /myfiles/data/
