### ISSUE TITLE
Range Degradation showing excessive miles

### ISSUE THREAD

**Issue by cwanja** [jheredianet/Teslamate-CustomGrafanaDashboards#89]
Hey @jheredianet

Got the release of the new dashboards. However, the Range Degradation dashboard is showing that Model S at one point had over 600 miles of estimate range. Calculation seems off.
<img width="503" alt="Screenshot 2024-06-26 at 8 34 27 PM" src="https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/assets/54645561/cb1b2d60-f16b-4363-be4f-11b6e95d7b8f">

**Comment by jheredianet** [comment]
Hi @cwanja 
Great catch! You are right, I was missing to convert the units.
It's already fixed now. Please, could you update again?

**Comment by cwanja** [comment]
Looks great now! Thanks @jheredianet
